poke 3.3
mistydemeo/tigerbrew pull request #1043
Opened 2023-12-02 22:53 UTC by sevan

Tested on Tiger (G5) with GCC 4.0.1.

Should be merged after #1042 since the new version of gettext includes a library called libtextstyle which poke would like to use and warns about it not being present when built against older versions lacking the library.

2023-12-27 07:12 UTC, mistydemeo requested changes
It didn't build for me until I added `libatomic_ops` as a dependency; mind adding that?

2023-12-27 18:09 UTC, mistydemeo commented
In my case it tried and failed to link against it until I added the direct dep. Maybe worth adding it to be safe?

2023-12-27 22:28 UTC, sevan commented
ah, ok, I've recreated the issue.
The `libatomic_ops` dependency gets added into the poke build process because poke's build uses pkg-config & `Cellar/bdw-gc/7.6.12/lib/pkgconfig/bdw-gc.pc` has `Libs: -L${libdir} -latomic_ops -lgc` but in `bdw-gc.rb` the `libatomic_ops` dependency is marked only for build, so if you've bottled it in a pristine env, the dependency will be missing. I'm just building stuff in place which is why we were getting different results.
With a successful build of poke, libatomic is not linked against in the resulting library nor binaries.

2023-12-27 22:49 UTC, sevan commented
Adjusted the libatomic dependency in bdw-gc's formula so hopefully this issue doesn't arise in the future. #1055

2024-01-26 05:39 UTC, mistydemeo approved these changes
Tested with GCC 4.2, and still failing, so left that `fails_with`.

2024-01-26 05:39 UTC, merged